pipeline {
    agent any 
    tools {
        maven "Maven 3.9.2"
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Static Code Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh 'mvn clean verify sonar:sonar -Dsonar.projectKey=cloud-infra'
                }
            }
        }
        stage("Quality Gate") {
            steps {
                  timeout(time: 1, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                  }
            }
        }


        stage('Build Hadoop Job') {
            steps {
                sh 'mvn package'
            }
        }

        stage('Deploy to Hadoop') {
            when {
                expression { currentBuild.resultIsBetterOrEqualTo('SUCCESS') }
            }
            steps {
                script {
                    sh '''
                      echo "This is a work in progress :)"
                    '''
                }
            }
        }

    }
}
