pipeline {
    agent any 
    tools {
        maven "Maven 3.9.2"
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Static Code Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh 'mvn clean verify sonar:sonar -Dsonar.projectKey=cloud-infra'
                }
            }
        }
        stage("Quality Gate") {
            steps {
                  timeout(time: 1, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                  }
            }
        }
    }
}
